//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tirage_Champions.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"Aatrox,Akali,Camille,Cho'Gath,Darius,Dr. Mundo,Fiora,Gangplank,Garen,Gnar,Gragas,Gwen,Heimerdinger,Illaoi,Irelia,Jax,Jayce,Kayle,Kennen,Kled,Lee Sin,Lucian,Maokai,Mordekaiser,Nasus,Nocturne,Ornn,Pantheon,Poppy,Quinn,Renekton,Rengar,Riven,Rumble,Ryze,Sett,Shen,Singed,Sion,Sylas,Teemo,Trundle,Tryndamere,Urgot,Vayne,Viego,Vladimir,Volibear,Warwick,Wukong,Yasuo,Yone,Yorick,Zac")]
        public string ChampionsNames {
            get {
                return ((string)(this["ChampionsNames"]));
            }
            set {
                this["ChampionsNames"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ChampionsForHasard {
            get {
                return ((string)(this["ChampionsForHasard"]));
            }
            set {
                this["ChampionsForHasard"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ChampionsSelected {
            get {
                return ((string)(this["ChampionsSelected"]));
            }
            set {
                this["ChampionsSelected"] = value;
            }
        }
    }
}
